version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-task-poc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1t1ayls8y7klt"
s3_prefix = "sam-task-poc"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
